fieldLayouts:
  cbb65259-2926-4d90-97fe-cd48c966d887:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7018c82d-5833-42df-b619-67c85e1865c0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 26cc7140-91ae-43f8-abb3-c70f60031f8b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fe503ef1-0e62-403d-b2e1-7c2762897dfe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bf1fa3b4-4bc6-42e5-8f96-d238e9a1b7b3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bcae0e12-3691-4204-b587-c9a36ff8b257
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e6390016-387f-4f7f-b59b-960b51896c69 # Matrix - Save to site where created in
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f0922f77-b226-4e79-9c0e-582ba92bc881
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5b680747-312a-49c7-b123-f7427e8aa631
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 01d4a96a-3bb7-4503-9e17-c009bd8c0c1d # Custom Propagating Pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
