childBlocks: null
conditions: null
description: ''
enabled: true
field: 26cc7140-91ae-43f8-abb3-c70f60031f8b # Neo
fieldLayouts:
  1c417933-7a70-4180-bee6-dd829a8e9a15:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 55658cdd-ca31-406a-bbd3-1273692ceff0 # Super Table
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 12723a89-4be4-437a-b6ae-022c18fe1783
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7f13f666-6f8b-4969-974e-d12cb437e3c7
        userCondition: null
group: null
groupChildBlockTypes: true
handle: superTable
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Super Table'
sortOrder: 2
topLevel: true
