childBlocks: null
conditions: null
description: ''
enabled: true
field: 8ffd3c5b-2d9a-4cb8-ad3f-b5b14fd0ad94 # Neo - Save blocks to all sites the owner element is saved in
fieldLayouts:
  0460db09-7060-47f6-9775-b03b3f0cb026:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 55658cdd-ca31-406a-bbd3-1273692ceff0 # Super Table
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: be5faf76-eef0-45d3-8da2-fa11a5d18d23
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 43d0a092-09a9-40c5-a685-9ec005b41b2a
        userCondition: null
group: null
groupChildBlockTypes: true
handle: superTable
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Super Table'
sortOrder: 2
topLevel: true
