childBlocks: null
conditions: null
description: ''
enabled: true
field: bf1fa3b4-4bc6-42e5-8f96-d238e9a1b7b3 # Neo - Save blocks to the site where they were created in 2
fieldLayouts:
  da7bf725-e605-49c9-bb02-649b1e8a5fd5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 55658cdd-ca31-406a-bbd3-1273692ceff0 # Super Table - Save blocks to all sites the owner element is saved in
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 36802bce-894c-4a89-aac0-64432c6c0d4b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3b9b4c81-e2c0-47cb-a977-e4bf8fc1e3ad
        userCondition: null
group: null
groupChildBlockTypes: true
handle: superTableOwnerSaved
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Super Table Owner Saved'
sortOrder: 2
topLevel: true
