childBlocks: null
conditions: null
description: ''
enabled: true
field: 8ffd3c5b-2d9a-4cb8-ad3f-b5b14fd0ad94 # Neo - Save blocks to all sites the owner element is saved in
fieldLayouts:
  9230702f-8db0-448f-a8fb-88eb2d956184:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6cbef2c4-fa27-45aa-9ecb-8176e9840c19 # Non Translatable Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2137df0b-ccd9-4b05-80c6-33d5ba3bbae2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 03c5daa0-d679-44db-ac24-ebec86d5b20d
        userCondition: null
group: null
groupChildBlockTypes: true
handle: text
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Text
sortOrder: 1
topLevel: true
