childBlocks: null
conditions: null
description: ''
enabled: true
field: 26cc7140-91ae-43f8-abb3-c70f60031f8b
fieldLayouts:
  34b90d46-5c3b-404c-8e5e-2c3c9f81157f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6cbef2c4-fa27-45aa-9ecb-8176e9840c19
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1fb3c10e-c0d0-4981-b955-338e17a30aae
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c52823e4-2f59-4c8c-b463-9def6f6fe57f
        userCondition: null
group: null
groupChildBlockTypes: true
handle: text
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Text
sortOrder: 1
topLevel: true
