childBlocks: null
conditions: null
description: ''
enabled: true
field: bf1fa3b4-4bc6-42e5-8f96-d238e9a1b7b3 # Neo - Save blocks to the site where they were created in 2
fieldLayouts:
  0d89d509-546a-4be7-8a41-62b9cd423740:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 6cbef2c4-fa27-45aa-9ecb-8176e9840c19 # Non Translatable Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71ff8821-4b1b-4728-8d2d-b3753fbebb0f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 80366057-85e7-4cdc-a268-c5b40621cc05
        userCondition: null
group: null
groupChildBlockTypes: true
handle: text
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Text
sortOrder: 1
topLevel: true
