columnSuffix: null
contentColumnType: string
fieldGroup: 53b4eb18-3aa6-45be-a772-5cb5fb567e50 # Common
handle: neoSiteCreated
instructions: null
name: 'Neo - Save blocks to the site where they were created in'
searchable: false
settings:
  maxBlocks: null
  maxLevels: null
  maxTopBlocks: null
  minBlocks: null
  minLevels: null
  minTopBlocks: null
  propagationKeyFormat: null
  propagationMethod: none
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
