columnSuffix: uqvzfcdv
contentColumnType: text
fieldGroup: 53b4eb18-3aa6-45be-a772-5cb5fb567e50 # Common
handle: nonTranslatableText
instructions: null
name: 'Non Translatable Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
