columnSuffix: null
contentColumnType: string
fieldGroup: 53b4eb18-3aa6-45be-a772-5cb5fb567e50 # Common
handle: superTable
instructions: null
name: 'Super Table'
searchable: false
settings:
  blockTypeFields: 0
  changedFieldIndicator: 514555301
  contentTable: '{{%stc_supertable}}'
  fieldLayout: table
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: null
  staticField: null
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
