columnSuffix: null
contentColumnType: string
fieldGroup: 53b4eb18-3aa6-45be-a772-5cb5fb567e50 # Common
handle: superTableOwnerSaved
instructions: null
name: 'Super Table - Save blocks to all sites the owner element is saved in'
searchable: false
settings:
  blockTypeFields: 0
  changedFieldIndicator: 1064307523
  columns:
    __assoc__:
      -
        - c745f85f-2215-45dd-9088-4c23411c29b7 # Text
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_supertableownersaved}}'
  fieldLayout: table
  maxRows: null
  minRows: null
  propagationKeyFormat: null
  propagationMethod: all
  selectionLabel: null
  staticField: null
translationKeyFormat: null
translationMethod: none
type: verbb\supertable\fields\SuperTableField
