dateModified: 1693595416
email:
  fromEmail: test@example.org
  fromName: 'Test Propagation'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    01d4a96a-3bb7-4503-9e17-c009bd8c0c1d: 'Custom Propagating Pages' # Custom Propagating Pages
    2ddc08b2-3d60-49e3-a30d-0163f58cf994: Default # Default
    3d2b09f3-1f02-43eb-97a0-e651202d5ffd: Text # Text
    8e565415-bfff-4359-8734-2cc58b1220f8: Text # Text
    53b4eb18-3aa6-45be-a772-5cb5fb567e50: Common # Common
    68d65960-3b6f-4154-8541-b62ae3389768: Text # Text
    287e3fdb-5d34-4ec7-803e-4a8e02e050df: 'Spanish Site' # Spanish Site
    09307d04-3796-4a95-81ab-d21040fc43b1: Text # Text
    a4a434e9-33a0-4f16-82f0-94351c2a6a7e: 'English Site' # English Site
    b7369c19-9f40-4d20-849a-bcfa0ce9dedd: 'Test Propagation' # Test Propagation
    c745f85f-2215-45dd-9088-4c23411c29b7: Text # Text
    c956b8ba-e391-4fcd-9577-766cc240d399: Text # Text
    e6390016-387f-4f7f-b59b-960b51896c69: 'Matrix - Save to site where created in' # Matrix - Save to site where created in
    f6a76cdb-9dca-4e12-ac31-9fb51c5e4976: Text # Text
system:
  edition: solo
  live: true
  name: 'Test Propagation'
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
