dateModified: 1693591978
email:
  fromEmail: test@example.org
  fromName: 'Test Propagation'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    01d4a96a-3bb7-4503-9e17-c009bd8c0c1d: 'Custom Propagating Pages' # Custom Propagating Pages
    2be782d7-d238-4097-aa85-fba290c6e82b: 'Super Table' # Super Table
    2ddc08b2-3d60-49e3-a30d-0163f58cf994: Default # Default
    3d2b09f3-1f02-43eb-97a0-e651202d5ffd: Text # Text
    6cbef2c4-fa27-45aa-9ecb-8176e9840c19: 'Non Translatable Text' # Non Translatable Text
    8e565415-bfff-4359-8734-2cc58b1220f8: Text # Text
    8ffd3c5b-2d9a-4cb8-ad3f-b5b14fd0ad94: 'Neo - Save blocks to all sites the owner element is saved in' # Neo - Save blocks to all sites the owner element is saved in
    26cc7140-91ae-43f8-abb3-c70f60031f8b: 'Neo - Save blocks to the site where they were created in' # Neo - Save blocks to the site where they were created in
    53b4eb18-3aa6-45be-a772-5cb5fb567e50: Common # Common
    61bdd256-ea26-4e78-8e23-db5bc473c427: 'Super Table Owner Saved' # Super Table Owner Saved
    68d65960-3b6f-4154-8541-b62ae3389768: Text # Text
    287e3fdb-5d34-4ec7-803e-4a8e02e050df: 'Spanish Site' # Spanish Site
    09307d04-3796-4a95-81ab-d21040fc43b1: Text # Text
    55658cdd-ca31-406a-bbd3-1273692ceff0: 'Super Table - Save blocks to all sites the owner element is saved in' # Super Table - Save blocks to all sites the owner element is saved in
    061892d7-36f3-4f27-ae73-8e44cc1d3af9: 'Super Table' # Super Table
    94576b58-ba85-4404-974b-5722622f7c80: 'Super Table - Save blocks to the site where they were created in' # Super Table - Save blocks to the site where they were created in
    a4a434e9-33a0-4f16-82f0-94351c2a6a7e: 'English Site' # English Site
    b7369c19-9f40-4d20-849a-bcfa0ce9dedd: 'Test Propagation' # Test Propagation
    bf1fa3b4-4bc6-42e5-8f96-d238e9a1b7b3: 'Neo - Save blocks to the site where they were created in 2' # Neo - Save blocks to the site where they were created in 2
    c1b63714-b449-43d0-b74f-4ed021d0f707: Text # Text
    c745f85f-2215-45dd-9088-4c23411c29b7: Text # Text
    c956b8ba-e391-4fcd-9577-766cc240d399: Text # Text
    e6390016-387f-4f7f-b59b-960b51896c69: 'Matrix - Save to site where created in' # Matrix - Save to site where created in
    f6a76cdb-9dca-4e12-ac31-9fb51c5e4976: Text # Text
    f9134697-47a3-4643-8d5a-e0d26b292438: 'Super Table Owner Saved' # Super Table Owner Saved
plugins:
  neo:
    edition: standard
    enabled: true
    licenseKey: VDTP7391BMA1W4NOO3867YGH
    schemaVersion: 3.6.2
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
system:
  edition: solo
  live: true
  name: 'Test Propagation'
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
