dateModified: 1692198846
email:
  fromEmail: test@example.org
  fromName: 'Test Propagation'
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    53b4eb18-3aa6-45be-a772-5cb5fb567e50: Common # Common
    a4a434e9-33a0-4f16-82f0-94351c2a6a7e: 'Test Propagation' # Test Propagation
    b7369c19-9f40-4d20-849a-bcfa0ce9dedd: 'Test Propagation' # Test Propagation
system:
  edition: solo
  live: true
  name: 'Test Propagation'
  schemaVersion: 4.4.0.4
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
