changedFieldIndicator: 374438880
field: 55658cdd-ca31-406a-bbd3-1273692ceff0 # Super Table
fieldLayouts:
  5a80d396-927a-4adf-a9a3-83e8996d31e3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c745f85f-2215-45dd-9088-4c23411c29b7 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2938d61-be4b-4a5b-b400-a7906cd3702a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b8bf6614-d50d-4251-bed7-73f6db17db69
        userCondition: null
fields:
  c745f85f-2215-45dd-9088-4c23411c29b7: # Text
    columnSuffix: agysluvx
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
