changedFieldIndicator: 1016974375
field: 94576b58-ba85-4404-974b-5722622f7c80 # Super Table - Save blocks to the site where they were created in
fieldLayouts:
  c7951ec2-46ff-4998-932b-6d1a6df1c809:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c956b8ba-e391-4fcd-9577-766cc240d399 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 621b8119-36dd-415f-9cb3-e0ac38b143d4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 83409af0-565a-4493-a0f7-f149889ca364
        userCondition: null
fields:
  c956b8ba-e391-4fcd-9577-766cc240d399: # Text
    columnSuffix: lqsjsors
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
